---
- name: Install required packages for certman
  yum: name={{ item }} state=installed
  with_items:
  - python-yaml
  when: certman_enabled

- name: Make necessary directories
  file: path={{ item }} owner=root group=root mode=0755 state=directory
  with_items:
  - "{{ docroot }}"
  - "{{ docroot }}/{{ acme_challenge_dir }}"
  - "{{ remote_cert_store }}"
  - "{{ certman_config_directory }}"

- name: Make an account key if we don't have one
  shell: openssl genrsa 4096 > {{ remote_cert_store}}/letsencrypt-account.key
  args:
    creates: "{{ remote_cert_store}}/letsencrypt-account.key"

- name: Copy certman to the server
  copy: src=../files/certman dest=/usr/local/bin/certman owner=root group=root mode=0755
  when: certman_enabled

- name: Install acme_tiny if required
  git: repo='https://github.com/diafygi/acme-tiny.git' dest="{{ letsencrypt_acme_tiny_dir }}" update=no
  when: letsencrypt_install_acme_tiny

- name: Install crontab for certman
  template: src=../templates/cron.daily.j2 dest=/etc/cron.daily/certman owner=root group=root mode=0755
  when: certman_enabled

